### ISSUE TITLE
书中提供的视频地址都无法观看

### ISSUE THREAD

**Issue by MrGuang123** [ikcamp/koa-miniprogram#48]
https://ikcamp.com/和https://camp.qianduan.group/koa2/2/0/0两个视频地址都无法打开，麻烦作者查看下原因或者提供一下其他观看的方法，谢谢

**Comment by BruceCham** [comment]
@MrGuang123  您好，麻烦您试一下这个看能解决不？ [koa2-tutorial/issues/44](https://github.com/ikcamp/koa2-tutorial/issues/44)

**Comment by MrGuang123** [comment]
可以看了，多谢
